# This workflow makes sure edge case versions work
name: Test Installation

on:
  pull_request:
    branches:
      - master
    paths:
      - "**.py"
      - ".github/workflows/**.yml"

jobs:
  test-installation:
    strategy:
      max-parallel: 12
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.6.8, 3.7, 3.8, 3.9]
        torch-version: [1.7.1]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install PyTorch Linux and MacOS
        if: startsWith(runner.os, 'Windows') != true
        env:
          TORCH_VERSION: ${{ matrix.torch-version }}
          TORCHVISION_VERSION: "0.8.2"
        run: |
          pip install torch==${TORCH_VERSION} torchvision==${TORCHVISION_VERSION}

      - name: Install PyTorch Windows
        if: startsWith(runner.os, 'Windows')
        env:
          TORCH_VERSION: ${{ matrix.torch-version }}
          TORCHVISION_VERSION: "0.8.2"
        run: |
          pip install torch==$env:TORCH_VERSION+cpu torchvision==$env:TORCHVISION_VERSION+cpu -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install Opacus in Editing Mode
        run: |
          pip install -e . --default-timeout=60
